Add Create-UI and refine copy and layout of Build Apps landing page
vectara/vectara-docs pull request #230
Opened 2024-01-25 19:15 UTC by cjcenizal

2024-01-25 19:24 UTC, mrderyk requested changes
One typo and some non-blocking notes. :)

2024-01-25 19:24 UTC, mrderyk commented on www/docs/build-apps/app-building.md
> +Sample templates for pulling data from many popular data sources.
I'm not sure this fully encompasses what vectara-ingest is. The templates themselves are only configuration files, but vectara-ingest also includes [the various crawlers](https://github.com/vectara/vectara-ingest/tree/main/crawlers) that actually consume those configurations.

2024-01-25 19:24 UTC, mrderyk commented on www/docs/build-apps/react-search.md
> +The Reach-Search component pulls data from your Vectara account and adds
typo: Reach -> React

2024-01-25 19:24 UTC, mrderyk commented on www/docs/build-apps/react-search.md
> +The Reach-Search component pulls data from your Vectara account and adds
Do we want to say account or use corpora/datastore instead, for consistency of terminology?

2024-01-25 19:27 UTC, cjcenizal commented on www/docs/build-apps/app-building.md
> +Sample templates for pulling data from many popular data sources.
You're right. I was thinking of the crawlers as a form of template, too. Or at least it would be implied that they're included, otherwise what would you do with the templates? Do you think folks will be confused?

2024-01-25 19:30 UTC, cjcenizal commented on www/docs/build-apps/app-building.md
> +Sample templates for pulling data from many popular data sources.
Never mind, better to be safe than sorry. :) Incorporated your suggestion.

2024-01-25 19:30 UTC, cjcenizal commented
@mrderyk I addressed your comments. Can you take another look?

2024-01-26 16:55 UTC, mrderyk approved these changes

2024-01-26 18:14 UTC, merged