Add docs for stream concatenation, React-Chatbot, and Stream-Query-Client
vectara/vectara-docs pull request #260
Opened 2024-04-03 23:46 UTC by cjcenizal

2024-04-03 23:55 UTC, pwoznic requested changes
Just one typo and then lines 80 char (ignore the URLs adding to length of line)

2024-04-03 23:55 UTC, pwoznic commented on www/docs/api-reference/search-apis/stream-query.md
> +The consuming code must combing the stream's chunks as it receives them. The best method for doing so will depend on the language being used.
"combine"

Also, lines should be at or under 80 chars

2024-04-04 01:00 UTC, mrderyk approved these changes

2024-04-04 01:51 UTC, cjcenizal commented
Thanks @pwoznic ! I addressed your comments. Please merge this as soon as possible.

2024-04-04 02:26 UTC, pwoznic approved these changes
LGTM

2024-04-04 02:33 UTC, merged