Add User Defined Functions Reranker content
vectara/vectara-docs pull request #314
Opened 2024-08-12 18:26 UTC by pwoznic

Updated the Reranking section with information about the new User Defined Functions Rerankers. I also reorganized this section with the other available rerankers.

2024-08-12 18:43 UTC, nikron requested changes

2024-08-12 18:43 UTC, nikron commented on www/docs/api-reference/search-apis/reranking.md
> +* [Multilingual Reranker v1](/docs/learn/vectara-multi-lingual-reranker) `272725719` for accurate results across over 100 languages.
Should we call this slingshot? Also we don't really use the number for apiv2. We have "types" of rerankers. Slingshot type is "customer_specific"

2024-08-12 18:43 UTC, nikron commented on www/docs/api-reference/search-apis/reranking.md
> +* [Maximal Marginal Relevance (MMR) Reranker](/docs/learn/mmr-reranker) (`272725718`) for diversifying results while maintaining relevance.
this number isn't used in apiv2, it's just type=mmr

2024-08-12 18:43 UTC, nikron commented on www/docs/api-reference/search-apis/reranking.md
> +* [User Defined Function Reranker](/docs/learn/user-defined-function-reranker) `272725722` for custom scoring based on metadata.
userfn is the type, number is not used in apiv2

2024-08-12 18:43 UTC, nikron commented on www/docs/api-reference/search-apis/reranking.md
> +To enable reranking, specify the appropriate value for the `reranker_id`.
this works differently in apiv2, can you look at the reference and update?

2024-08-12 18:43 UTC, nikron commented on www/docs/learn/user-defined-function-reranker.md
> +literals are enclosed in single quotes (`‘`). To encode a single quote requires
wrong quote is used here, it should be ' instead of backtick

2024-08-12 18:43 UTC, nikron commented on www/docs/learn/user-defined-function-reranker.md
> +```json
type is wrong here

2024-08-12 18:43 UTC, nikron commented on www/docs/learn/user-defined-function-reranker.md
> +    "interpolated_score": .34
this is just interpolated, not interpolated score

2024-08-12 18:43 UTC, nikron commented on www/docs/learn/user-defined-function-reranker.md
> +    "interpolated_score": .34
also there is a "last" score which the last reranker or interpolated score computed

2024-08-12 19:22 UTC, pwoznic commented on www/docs/api-reference/search-apis/reranking.md
> +* [Multilingual Reranker v1](/docs/learn/vectara-multi-lingual-reranker) `272725719` for accurate results across over 100 languages.
Not sure if Slingshot is just an internal name

2024-08-13 18:19 UTC, nikron commented on www/docs/api-reference/search-apis/reranking.md
> +* [Maximal Marginal Relevance (MMR) Reranker](/docs/learn/mmr-reranker) (`272725718`) for diversifying results while maintaining relevance.
so for customer_specific you need to set the reranker_id

2024-08-13 18:19 UTC, nikron commented
Looks good; only error is that customer_specific type does require a reranker id. which would be rnk_{old id}

2024-08-13 18:49 UTC, nikron commented
did some edits on the udf-reranker page to fix some examples / flesh out get documentation.

2024-08-14 08:25 UTC, eskibars requested changes
Thanks for the draft @pwoznic.  I left some comments/suggestions

2024-08-14 08:25 UTC, eskibars commented on www/docs/learn/user-defined-function-reranker.md
> +search result.
Since this section is talking about interpolated and hybrid search scores here, it might warrant a link to the hybrid search docs and/or give a brief primer of what each of these scores actually mean here

2024-08-14 08:25 UTC, eskibars commented on www/docs/learn/user-defined-function-reranker.md
> +* `previous` - The last score computed by the retrieval pipeline. Most often
I think this needs a bit more detail.  I believe this is the score of the previous result, e.g. if the reranker is running on the 6th result, this contains the score of the 5th result post-reranking.  Is that accurate @nikron ?  I imagine folks will be wondering what to do with that score and use cases as well, which we can put an example for

2024-08-14 08:25 UTC, eskibars commented on www/docs/learn/user-defined-function-reranker.md
> +#### Lexical score example
I think we should craft new examples here because you could essentially do any of the following 3 without any reranker by just changing lambda.  That might be worth explaining in and of itself ("The following is essentially the same as setting lambda = 0 or lambda = 1 ...") and I think we should provide guidance here that _most_ users will likely want to use scores.interpolated and vary lambda in the hybrid search field, but that all scores are available.

But I think the more interesting examples are actually where the score gets combined in some fashion or wholesale replaced to implement metadata sorting.  e.g.:
- get('$.scores.interpolated') + get('$.document_metadata.average_review_score')/10 to bias higher-rated products
- get('$.scores.interpolated') - (to_unix_timestamp(now()) - get('$.document_metadata.date_epochseconds')) to bias toward newness
- if get('$.document_metadata.units_in_stock') > 0 then get('$.scores.interpolated') else 0 to give all items that are out of stock a score of 0 so they show up at the end

2024-08-14 08:25 UTC, eskibars commented on www/docs/learn/user-defined-function-reranker.md
> +and lexiccal results that find laptops which are both affordable and suitable
lexiccal

2024-08-14 08:25 UTC, eskibars commented on www/docs/learn/user-defined-function-reranker.md
> +previous searches:
I don't think this example is accurate?  @nikron

2024-08-14 08:25 UTC, eskibars commented on www/docs/learn/user-defined-function-reranker.md
> +| `seconds(a)`         | Converts a duration to the number of seconds.                 | `seconds(seconds(50))`             |
@nikron @pwoznic is this double-casting accurate?  e.g. seconds(seconds()), minutes(minutes()) and hours(hours()) or should these be singular?

2024-08-14 08:25 UTC, eskibars commented on www/docs/learn/user-defined-function-reranker.md
> +This example of a toy shows how ranking in an ecommerce system would work:
A toy?

2024-08-14 15:34 UTC, nikron commented on www/docs/learn/user-defined-function-reranker.md
> +* `previous` - The last score computed by the retrieval pipeline. Most often
no, it's the last previous reranker score if there are two rerankers scored together, or the final score of the chain. his name was too confusing and i'm eliminating it

2024-08-14 15:52 UTC, nikron commented on www/docs/learn/user-defined-function-reranker.md
> +previous searches:
removing previous

2024-08-14 15:56 UTC, nikron commented on www/docs/learn/user-defined-function-reranker.md
> +| `seconds(a)`         | Converts a duration to the number of seconds.                 | `seconds(seconds(50))`             |
Yes this is accurate; same function can cast a number to a double and vice versa.

2024-08-14 18:53 UTC, nikron commented
@pwoznic we decided to remove the scores object. i added more docs on scores

2024-08-15 11:28 UTC, cjcenizal commented on www/docs/learn/user-defined-function-reranker.md
> +The User Defined Functions Reranker enables users to define custom reranking
Let's preface every doc with a simple, accessible description of the problem that's being solved with the feature described by the doc. For example:

```
Our out-of-the-box rerankers are effective for general use cases, but some specific use cases require fine-grained control over how search results are ordered. For example, bubbling recently-added documents to the top, or limiting search results to a specific geolocation.
```

2024-08-15 12:25 UTC, merged