Add Generation Presets content to docs
vectara/vectara-docs pull request #318
Opened 2024-08-15 22:38 UTC by pwoznic

Added Generation presets to Query API Definition, API Reference, and some misc updates around response languages and FCS.

2024-08-16 15:49 UTC, nikron requested changes

2024-08-16 15:49 UTC, nikron commented on www/docs/api-reference/generation-presets/list-generation-presets.md
> +The `generation-preset-name` field replaces the `prompt_name` field that was in the
generation_preset_name

2024-08-16 15:49 UTC, nikron commented on www/docs/api-reference/generation-presets/list-generation-presets.md
> +work
trailing word

2024-08-16 15:49 UTC, nikron commented on www/docs/api-reference/search-apis/search.md
> +- `generation` - Specifies the summarization parameters and generation presets.
and the generation preset?

2024-08-16 15:49 UTC, nikron commented on www/docs/api-reference/search-apis/search.md
> +If you need more customization beyond what is available in the presets,
if you need to change generation beyond what the preset sets?

something like that

also only scale customers can do the majority of preset overries at this piont

2024-08-16 15:49 UTC, nikron commented on www/docs/api-reference/generation-presets/list-generation-presets.md
> +parameters. Presets are typically associated with specific LLMs, though some
a preset is currently associated with a single llm at this time.

2024-08-21 05:07 UTC, pwoznic commented
I think I addressed them all :)

2024-09-04 19:20 UTC, tallatshafaat commented
The list-generation-presets API reference is appearing weirdly: https://deploy-preview-318--luxury-shortbread-acee05.netlify.app/docs/rest-api/list-generation-presets

2024-09-04 20:37 UTC, merged