Update Chain Reranker topic about the array and examples
vectara/vectara-docs pull request #330
Opened 2024-09-24 23:24 UTC by pwoznic

Updated the description of the chain reranker and also added another example

2024-09-25 09:04 UTC, eskibars requested changes
Mostly minor comments, but 1 that I think we should review: we need to revise how we're talking about the multilingual reranker.  I've left comments in here to give some additional background for you, but we should probably discuss further to make sure you're up to speed on this feature.  Can you also double check the rest of the docs to see if we mention this elsewhere?

2024-09-25 09:04 UTC, eskibars commented on www/docs/learn/chain-reranker.md
> +example can be useful for multilingual content platforms such as blogs, news
The examples here should be refined for the same reasons as above with the multilingual reranker.  It doesn't really have to do with multilingual content -- it just gives better ranking order than Boomerang (and it just so happens that it can do that across 100 languages)

2024-09-30 20:39 UTC, pwoznic commented
I added the cutoffs property and updated the multilingual reranker verbiage in the latest commit.

2024-10-02 19:41 UTC, eskibars approved these changes

2024-10-02 20:09 UTC, merged