Update analytics to use rdcndn
vectara/vectara-docs pull request #37
Opened 2023-04-05 21:26 UTC by cjcenizal

Per guidance from @vklimontovich, this reverts https://github.com/vectara/vectara-docs/pull/16. The rdcdn file will be actively maintained, and we're going to remove the file hosted by Console.

@eskibars We also need to update the discuss forums to load this file from rdcdn. Can you help me with that?

CC @talip

2023-04-05 21:27 UTC, cjcenizal commented on www/static/analytics.js
> -    const cdnLink = "https://console.vectara.com/rd.js";
This is the only substantial change. The rest are formatting changes.

2023-04-06 03:32 UTC, eskibars requested changes

2023-04-06 03:32 UTC, eskibars commented on www/static/analytics.js
> +    const cdnLink = "https://rdcdn.vectara.com/v1.1/rudder-analytics.min.js";
We moved away from using `rudder-analytics.min.js` as the filename to `rd.js`.  Details at https://vectara.slack.com/archives/C03TKBKDZU4/p1672937342352849 and I or Talip can chat more with you as well if you'd like

2023-08-09 15:18 UTC, cjcenizal commented
This change is no longer relevant.

2023-08-09 15:18 UTC, closed without merging