Rename corpus to index
vectara/vectara-docs pull request #77
Opened 2023-08-18 19:52 UTC by pwoznic

Renamed corpus to index in 4 topics

2023-08-18 20:23 UTC, eskibars requested changes
A few spelling modifications.  I'm OK with this, but I want to be prepared to revert if this doesn't meaningfully improve corpus creation metrics

2023-08-18 20:23 UTC, eskibars commented on www/docs/api-reference/admin-apis/delete-corpus.md
> +to injest content into an index:
s/injest/ingest/

2023-08-18 20:23 UTC, eskibars commented on www/docs/api-reference/admin-apis/delete-corpus.md
> +and the index will no longer be usable for future injesting or querying.
s/injesting/ingesting/

2023-08-18 20:23 UTC, eskibars commented on www/docs/api-reference/admin-apis/create-corpus.md
> +to injest content into an index:
s/injest/ingest/

2023-08-18 20:51 UTC, pwoznic commented on www/docs/api-reference/admin-apis/delete-corpus.md
> +to injest content into an index:
Whoops 😬

2023-08-18 20:52 UTC, pwoznic commented
I fixed the typos in the latest commit

2023-08-19 01:20 UTC, danielone commented
@pwoznic Great work! 
Only addition is I think we should introduce index/indicies verbiage in the body of creating a corpus
https://deploy-preview-77--luxury-shortbread-acee05.netlify.app/docs/console-ui/creating-a-corpus

Noteably the first line of text
"To get begin searching your data, you first have to create a corpus. A corpus is a container where you upload all your data to be indexed and grouped together in a single location for querying."

You may want to consider lightly adjusting some of the follow on text regarding corpus vs. index when it comes to what users should be clicking on and removing images as well, perhaps just including a single one. 

This document is directly linked to from the console. This way the flow from console -> docs for create corpus can be tied together in a minimal way.

2023-08-19 04:01 UTC, pwoznic commented
> @pwoznic Great work! Only addition is I think we should introduce index/indicies verbiage in the body of creating a corpus https://deploy-preview-77--luxury-shortbread-acee05.netlify.app/docs/console-ui/creating-a-corpus
> 
> Noteably the first line of text "To get begin searching your data, you first have to create a corpus. A corpus is a container where you upload all your data to be indexed and grouped together in a single location for querying."
> 
> You may want to consider lightly adjusting some of the follow on text regarding corpus vs. index when it comes to what users should be clicking on and removing images as well, perhaps just including a single one.
> 
> This document is directly linked to from the console. This way the flow from console -> docs for create corpus can be tied together in a minimal way.

Done :)

2023-08-19 05:04 UTC, cjcenizal approved these changes
Changes look great! Just had a few suggestions.

2023-08-19 05:04 UTC, cjcenizal commented on www/docs/api-reference/admin-apis/create-corpus.md
> +  // The index ID.
I can imagine folks being confused by this -- "Index ID? Corpus ID? What's the difference?" Can we clarify things a bit here? For example: "The index ID, also referred to as the corpus ID."

2023-08-19 05:04 UTC, cjcenizal commented on www/docs/api-reference/admin-apis/delete-corpus.md
> +and the index will no longer be usable for future ingesting or querying.
In this sentence, "querying" refers to the index as in "the index is queried". But "ingesting" doesn't refer to index in the same way -- "the index is ingested" is incorrect. I think it might be clearer to rephrase this as:

> the index will no longer be usable for data ingestion or querying

2023-08-19 05:04 UTC, cjcenizal commented on www/docs/api-reference/admin-apis/reset-corpus.md
> +To reset an index, specify the **customer id** and **corpus id**. Upon
Nit: Should "customer id" be `customer_id`, and "corpus id" be `corpus_id`, since we're referring to parts of the interface?

2023-08-19 05:04 UTC, cjcenizal commented on www/docs/api-reference/admin-apis/delete-corpus.md
> +  // The index is the Corpus ID to be deleted.
Similar concern here as above. Maybe, "The corpus ID uniquely identifies the index to delete"?

2023-08-19 05:04 UTC, cjcenizal commented on www/docs/api-reference/admin-apis/reset-corpus.md
> +  // The index is the Corpus ID to be reset.
Similar concern here as above. Maybe, "The corpus ID uniquely identifies the index to reset"?

2023-08-19 19:30 UTC, pwoznic commented on www/docs/api-reference/admin-apis/reset-corpus.md
> +  // The index is the Corpus ID to be reset.
I made the suggested changes for all of these

2023-08-19 19:30 UTC, pwoznic commented
Updated topics for more clarifications

2023-08-21 19:03 UTC, danielone approved these changes

2023-08-21 19:09 UTC, merged