Update key concepts
vectara/vectara-docs pull request #83
Opened 2023-08-28 22:45 UTC by pwoznic

Added this new topic in the Getting Started to provide an overview of conceptual topics in Gen AI. As we build out the new concepts chapter (Learn), we will link to the appropriate overview section for each term. I also created supporting diagrams for each section. I would like to create a more complex diagram that ties everything together in a future PR.

2023-08-29 00:07 UTC, cjcenizal requested changes
I think we should make some changes to this before merging. @amin2718 Would you mind reviewing my comments to ensure my takes are accurate?

I think we also need to adjust the AI Architecture image, to make the relationships between the boxes clearer. To move quickly we can just remove the lines connecting the boxes, but we can refine it further by making it clear that "Vector Databases" enable the various types of search, and then feed the result to "LLMs" to provide helpful answers to questions.

2023-08-29 00:07 UTC, cjcenizal commented on www/docs/key-concepts.md
> +### Hallucinations
How about changing this to "Reducing hallucination", since "Hallucination" isn't exactly a technique?

2023-08-29 00:07 UTC, cjcenizal commented on www/docs/key-concepts.md
> +present in the input or training data. Simply put, chatbots tend to make
I suggest removing the "Simply put..." sentence because I think it's an oversimplification and potentially misleading. The rest of the paragraph sounds accurate to me.

2023-08-29 02:34 UTC, pwoznic commented
> I think we should make some changes to this before merging. @amin2718 Would you mind reviewing my comments to ensure my takes are accurate?
> 
> I think we also need to adjust the AI Architecture image, to make the relationships between the boxes clearer. To move quickly we can just remove the lines connecting the boxes, but we can refine it further by making it clear that "Vector Databases" enable the various types of search, and then feed the result to "LLMs" to provide helpful answers to questions.

Sounds good. I originally wanted to create a diagram that covered everything but I thought it would be helpful to create a diagram for each section and we can discuss as a team on the best way to present the info, combine, etc. I will go through comments on what I can change.

2023-08-29 03:09 UTC, pwoznic reviewed
I made changes based on the comments

2023-11-03 19:24 UTC, pwoznic commented
We're working on a new key concepts now so closing this one.

2023-11-03 19:24 UTC, closed without merging