Add API Quickstart topic
vectara/vectara-docs pull request #84
Opened 2023-09-01 02:57 UTC by pwoznic

Added a quick start topic for the API called API Jumpstart. The intent is to show a variety of basic queries around searching, uploading files, updating metadata, listing indices, etc. This topic does not include humorous examples like the console quickstart because I started this draft a while ago. I can make the content more engaging and entertaining if necessary.

My vision is to have additional examples throughout the documentation that are more advanced and showcase more real-world situations that explain what we're doing and why, e.g. more examples about metadata.

2023-09-01 04:55 UTC, cjcenizal requested changes
This is fantastic content! I spotted some formatting problems I think we need to dig into and also had some other suggestions about content.

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +title: API Jumpstart
Can I suggest calling these "API recipes" or "App recipes" (I prefer this one) to avoid confusion between Quickstart and Jumpstart? I think the idea of "recipes" describes these nicely... you follow a few easy steps and you achieve a delicious outcome.

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +Using the API enables you to integrate the <Config v="names.product"/> search capabilities into your
We publish numerous APIs, not just a single one. So for consistency, I suggest referring to "our APIs" or "Vectara's APIs" instead of "the API".

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +testing and manual operations, the <Config v="names.product"/> API is where the
The Console UI and our APIs work hand-in-hand as part of the app development process. For example, a developer will:

1. Fine-tune a query's lambda and filters until the answer quality is just right.
2. Click "copy request" button and paste it into their IDE.
3. Copy their customer ID and API key from Console to further configure the request.
4. Test out their software and then verify requests are hitting their corpus by checking the querier graph on the Overview tab.

Generally, I think we should be careful to avoid casting Console as "less than" the APIs, because they are both part of a single product.

For this particular sentence, maybe we can just remove it?

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +```json
Oddly enough this highlights pretty nicely with `js`.

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +```json
I think this will highlight more nicely as `js`.

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +1. Execute the following cURL command:
In previous examples this is an h3. Should format this the same for consistency?

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> + You get the following response:
Same here.

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +   ```json
As with the other examples, this seems to format more nicely with `js`.

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +1. Execute the following curl command to list the indices:
Same comment here and elsewhere about using an h3.

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +1. Execute the following curl command to update an existing document in your
Not sure what's going on here but it looks like GitHub is getting confused about how to parse the Markdown here.

![image](https://github.com/vectara/vectara-docs/assets/1238659/cec0f4e6-a3da-47e4-8c8e-83ff2f293645)

2023-09-01 04:55 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +Thie API jumpstart provided a variety of query examples that you can leverage
Typo: "Thie" -> "This"

And if we go with "recipes" then we'll need to update the reference to "jumpstart".

2023-09-07 20:13 UTC, pwoznic reviewed
Addressed changes from comments

2023-09-08 21:45 UTC, cjcenizal approved these changes
Looks good! I still see some weird formatting issues in the preview, but maybe they won't show up in Docusaurus.

2023-09-08 21:45 UTC, cjcenizal commented on www/docs/api-jumpstart.md
> +3. Execute the curl command from Step 1 again:
Since there's no code snippet after this sentence, maybe it should be inlined with the following sentence?

```
3. Execute the curl command from Step 1 again. You get the following response:
```

2023-09-08 22:08 UTC, pwoznic reviewed
Updated step 3

2023-09-08 22:13 UTC, merged